---
- name: Install and Configure Apache Web Server
  hosts: webservers
  become: yes
  vars:
    apache_pkg: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
    apache_service: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
    web_root: "{{ '/var/www/html' if ansible_os_family == 'RedHat' else '/var/www/html' }}"

  tasks:
    - name: Install Apache package
      package:
        name: "{{ apache_pkg }}"
        state: present

    - name: Ensure Apache service is running and enabled
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: yes

    - name: Deploy custom index.html
      copy:
        dest: "{{ web_root }}/index.html"
        content: |
          <html>
          <head><title>Welcome</title></head>
          <body>
            <h1>Hello from Ansible 🚀</h1>
            <p>This web server is configured using Ansible on {{ ansible_distribution }}.</p>
          </body>
          </html>
        owner: root
        group: root
        mode: '0644'
