pipeline {
    agent any
    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/sachinashokyadav/devops_tools.git'
            }
        }

        stage('Deploy to EC2') {
    steps {
        sshagent (credentials: ['ec2-ssh-key']) {
            sh '''
                scp -o StrictHostKeyChecking=no Jenkins/Deploy-StaticWebsite-to-Apache-on-EC2/index.html ubuntu@65.2.177.68:/tmp/index.html

                ssh -o StrictHostKeyChecking=no ubuntu@65.2.177.68 "
                    sudo apt update -y
                    sudo apt install apache2 -y
                    sudo mv /var/www/html/index.html /var/www/html/index.html.bak || true
                    sudo mv /tmp/index.html /var/www/html/index.html
                    sudo systemctl restart apache2
                "
            '''
        }
    }
}


    }

    post {
        success {
            echo '✅ Deployment completed successfully!'
        }
        failure {
            echo '❌ Deployment failed.'
        }
    }
}
